// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC57b3SIBJ83tMHhqs6v_g_02obTDtb2-Y',
    appId: '1:456484047722:web:a4b1e198da6c6f334df313',
    messagingSenderId: '456484047722',
    projectId: 'final-project-8daa8',
    authDomain: 'final-project-8daa8.firebaseapp.com',
    storageBucket: 'final-project-8daa8.appspot.com',
    measurementId: 'G-7VGR64P1XJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7vNedAbHGO0WLnDTplqYPQtof7dqUJls',
    appId: '1:456484047722:ios:eb66019a328ba42a4df313',
    messagingSenderId: '456484047722',
    projectId: 'final-project-8daa8',
    storageBucket: 'final-project-8daa8.appspot.com',
    iosBundleId: 'com.example.dtreatyflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7vNedAbHGO0WLnDTplqYPQtof7dqUJls',
    appId: '1:456484047722:ios:eb66019a328ba42a4df313',
    messagingSenderId: '456484047722',
    projectId: 'final-project-8daa8',
    storageBucket: 'final-project-8daa8.appspot.com',
    iosBundleId: 'com.example.dtreatyflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC57b3SIBJ83tMHhqs6v_g_02obTDtb2-Y',
    appId: '1:456484047722:web:1b1c28985b17f23a4df313',
    messagingSenderId: '456484047722',
    projectId: 'final-project-8daa8',
    authDomain: 'final-project-8daa8.firebaseapp.com',
    storageBucket: 'final-project-8daa8.appspot.com',
    measurementId: 'G-RZLER1TJE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuTmn-Zb2glPjJyu-WmsFQw730uM_5f3M',
    appId: '1:456484047722:android:7568fcee0d8854084df313',
    messagingSenderId: '456484047722',
    projectId: 'final-project-8daa8',
    storageBucket: 'final-project-8daa8.appspot.com',
  );
}
